FROM ghcr.io/synthetixio/docker-node/alpine:%%TAG%%

RUN npm install -g lockfile-lint@%%LOCKFILE_LINT_VERSION%% npm-audit-ci-wrapper@%%NPM_AUDIT_WRAPPER_VERSION%% auditjs@%%AUDITJS_VERSION%%

RUN curl -LO https://storage.googleapis.com/container-diff/v%%CONTAINER_DIFF_VERSION%%/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && mv container-diff-linux-amd64 "$HOME"/bin/container-diff
