FROM ghcr.io/synthetixio/docker-node/base:%%TAG%%

RUN npm install -g audit-ci@%%AUDIT_CI_VERSION%% lockfile-lint@%%LOCKFILE_LINT_VERSION%%

RUN curl -LO https://storage.googleapis.com/container-diff/v%%CONTAINER_DIFF_VERSION%%/container-diff-linux-amd64 && chmod +x container-diff-linux-amd64 && mv container-diff-linux-amd64 "$HOME"/bin/container-diff
