name: Docker Image CI

on:
  push:
    branches: [master]
    paths:
      - "output/**"
      - ".github/workflows/docker-image.yml"

jobs:
  build_and_push:
    strategy:
      matrix:
        node: ["12.22", "14.18", "16.13", "17.3"]
        distro: [alpine, debian, ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee5a9d1395988d7c82c67c69571871f5994b94df # pin@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # pin@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # pin@v1

      - name: Cache Docker layers
        uses: actions/cache@3b70782066bd817837b6bd8c518d45b54d91bf76 # pin@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.node }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@6af3c118c8376c675363897acf1757f7a9be6583 # pin@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@6af3c118c8376c675363897acf1757f7a9be6583 # pin@v1
        with:
          registry: ghcr.io
          username: synthetixio
          password: ${{ secrets.GH_PACKAGES_READ_WRITE }}

      - name: Build and push (${{ matrix.distro }}[${{ matrix.node }}])
        uses: docker/build-push-action@1814d3dfb36d6f84174e61f4a4b05bd84089a4b9 # pin@v2
        with:
          context: .
          file: ./output/${{ matrix.distro }}/${{ matrix.node }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/synthetixio/${{ github.event.repository.name }}/${{ matrix.distro }}:${{ matrix.node }}
            synthetixio/${{ github.event.repository.name }}:${{ matrix.node }}-${{ matrix.distro }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
