name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build_and_push:
    strategy:
      matrix:
        node: [ '10.24', '10.24-npm6', '12.22', '12.22-npm6', '14.17', '15.11' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee5a9d1395988d7c82c67c69571871f5994b94df # pin@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c308fdd69d26ed66f4506ebd74b180abe5362145 # pin@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d135e0c2fc0dba0729c1a47ecfcf5a3c7f8579e # pin@v1

      - name: Cache Docker layers
        uses: actions/cache@3b70782066bd817837b6bd8c518d45b54d91bf76 # pin@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.node }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # pin@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 # pin@v1
        with:
          registry: ghcr.io
          username: synthetixio
          password: ${{ secrets.GH_PACKAGES_READ_WRITE }}

      - name: Build and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc # pin@v2
        with:
          context: .
          file: ./${{ matrix.node }}/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ghcr.io/synthetixio/${{ github.event.repository.name }}/base:${{ matrix.node }}
            synthetixio/${{ github.event.repository.name }}:${{ matrix.node }}

          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
