name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build_and_push:
    strategy:
      matrix:
        node: [ '10.24', '12.21', '14.16', '15.11' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee5a9d1395988d7c82c67c69571871f5994b94df # pin@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@6520a2d2cb6db42c90c297c8025839c98e531268 # pin@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@07b1484797040ef4a1109a03e65b923de8f39e07 # pin@v1

      - name: Cache Docker layers
        uses: actions/cache@3b70782066bd817837b6bd8c518d45b54d91bf76 # pin@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.node }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a # pin@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a # pin@v1
        with:
          registry: ghcr.io
          username: synthetixio
          password: ${{ secrets.GH_PACKAGES_READ_WRITE }}

      - name: Build and push
        uses: docker/build-push-action@6925f94b6b8f23d547930f88b9886036ac92d510 # pin@v2
        with:
          context: .
          file: ./${{ matrix.node }}/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ghcr.io/synthetixio/${{ github.event.repository.name }}/base:${{ matrix.node }}
            synthetixio/${{ github.event.repository.name }}:${{ matrix.node }}

          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
